MAX_STEER_TICKS: 8192
MAX_TRACT_TICKS: 5000

# initial values for the kinematic parameters and the relative position of the sensor aka my state X

INITIAL_K_STEER: 0.1
INITIAL_K_TRACT: 0.0106141
INITIAL_AXIS_LENGTH : 1.4
INITIAL_STEER_OFFSET : 0

INITIAL_LASER_WRT_BASE_X: 1.5
INITIAL_LASER_WRT_BASE_Y: 0
INITIAL_LASER_WRT_BASE_ANGLE: 0

STATE_DIM: 7
MEASUREMENT_DIM: 3
NUM_ITERATIONS: 10
DATA_SIZE: 2434
EPSILON: 1e-7