MAX_STEER_TICKS: 8192
MAX_TRACT_TICKS: 5000

# initial values for the kinematic parameters

INITIAL_K_STEER: 0.1
INITIAL_K_TRACT: 0.0106141
INITIAL_AXIS_LENGTH : 1.4
INITIAL_STEER_OFFSET : 0

# parameters useful to define the transformation

LASER_WRT_BASE_X: 1.5
LASER_WRT_BASE_ANGLE: 0